sudo: required
language: node_js
node_js:
  - "node"
  - "10"
  - "8"
  - "6"
env:
  global:
    - BACKEND_CPU=true EXCLUDE_UNCOMPRESSED=true
  matrix:
    - ENV=browser
    - ENV=node
addons:
  chrome: stable
install: npm install
before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
script:
  - if [ $ENV == 'browser' ]; then npm run test-browser; fi
  - if [ $ENV == 'node' ]; then npm run test-node; fi
  - npm run build